x=int(input("x: "))
y=int(input("y: "))
print("x += y: x =",x+y,"and y =",y)
print("x -= y: x =",x-y,"and y =",y)
print("x *= y: x =",x*y,"and y =",y)
print("x /= y: x =",x/y,"and y =",y)
print("x **= y: x =",x**y,"and y =",y)
print("x //= y: x =",x//y,"and y =",y)
print("x %= y: x =",x%y,"and y =",y)
print("x = y: x =",y,"and y =",y)
